### ISSUE TITLE
Uncaught Error: downloading plugin "autopilot_deno" from "https://github.com/divy-work/deno-tar/releases/latest/download/libautopilot_deno.dylib" failed.

### ISSUE THREAD

**Issue by bvenkatr** [divy-work/deno-tar#1]
Deno Version:- 1.0.4

deno run -A --unstable -r examples/archive.ts

Download https://deno.land/x/checksum@1.4.0/md5.ts
Compile file:///Users/user1/OneDrive/coding/deno-tar/examples/archive.ts
INFO downloading deno plugin "autopilot_deno" from "https://github.com/divy-work/deno-tar/releases/latest/download/libautopilot_deno.dylib"
error: Uncaught Error: downloading plugin "autopilot_deno" from "https://github.com/divy-work/deno-tar/releases/latest/download/libautopilot_deno.dylib" failed.
    throw Error(`downloading plugin "${name}" from "${remoteUrl}" failed.`);
          ^
    at downloadFromRemote (https://deno.land/x/plugin_prepare/mod.ts:76:11)
    at async download (https://deno.land/x/plugin_prepare/mod.ts:46:7)
    at async prepare (https://deno.land/x/plugin_prepare/mod.ts:60:21)
    at async file:///Users/user1/OneDrive/coding/deno-tar/plugin/index.ts:32:20

**Comment by littledivy** [comment]
@bvenkatr Thank you for opening the issue. I've fixed the issue. Please confirm if it works now.

**Comment by bvenkatr** [comment]
@divy-work I got another error

Mac OS:- 10.15.4 Catalina

deno run -A --unstable -r examples/archive.ts
Download https://deno.land/x/plugin_prepare/mod.ts
Download https://deno.land/std@0.51.0/async/mod.ts
Download https://deno.land/x/plugin_prepare/deps.ts
Download https://deno.land/std@0.51.0/async/deferred.ts
Download https://deno.land/std@0.51.0/async/delay.ts
Download https://deno.land/std@0.51.0/async/mux_async_iterator.ts
Download https://deno.land/std@v0.51.0/fs/exists.ts
Download https://deno.land/std@v0.51.0/log/mod.ts
Download https://deno.land/std@v0.51.0/path/mod.ts
Download https://deno.land/x/checksum@1.4.0/mod.ts
Download https://deno.land/std@v0.51.0/log/logger.ts
Download https://deno.land/std@v0.51.0/log/handlers.ts
Download https://deno.land/std@v0.51.0/testing/asserts.ts
Download https://deno.land/std@v0.51.0/log/levels.ts
Download https://deno.land/std@v0.51.0/path/win32.ts
Download https://deno.land/std@v0.51.0/path/posix.ts
Download https://deno.land/std@v0.51.0/path/common.ts
Download https://deno.land/std@v0.51.0/path/separator.ts
Download https://deno.land/std@v0.51.0/path/interface.ts
Download https://deno.land/std@v0.51.0/path/glob.ts
Download https://deno.land/x/checksum@1.4.0/hash.ts
Download https://deno.land/std@v0.51.0/path/_constants.ts
Download https://deno.land/std@v0.51.0/path/_util.ts
Download https://deno.land/std@v0.51.0/fmt/colors.ts
Download https://deno.land/std@v0.51.0/testing/diff.ts
Download https://deno.land/std@v0.51.0/path/_globrex.ts
Download https://deno.land/x/checksum@1.4.0/sha1.ts
Download https://deno.land/x/checksum@1.4.0/md5.ts
Compile file:///Users/user1/OneDrive/coding/deno-tar/examples/archive.ts
INFO downloading deno plugin "deno_tar" from "https://github.com/divy-work/deno-tar/releases/latest/download/libdeno_tar.dylib"
INFO load deno plugin "deno_tar" from local "/Users/user1/OneDrive/coding/deno-tar/.deno_plugins/deno_tar_d7e79555a7a99803be0f927465a8de5d.dylib"
Bus error: 10

**Comment by littledivy** [comment]
@bvenkatr Looks like a problem with Mac. I'll look into it. Could you try building it from source. `cargo build`

**Comment by bvenkatr** [comment]
bruh.tar file getting generated , but examples/read.ts not printing anything

IL1019:deno-tar user1$ cargo build
    Updating crates.io index
  Downloaded futures v0.3.5
  Downloaded serde_json v1.0.53
  Downloaded tar v0.4.28
  Downloaded serde v1.0.110
  Downloaded futures-io v0.3.5
  Downloaded futures-executor v0.3.5
  Downloaded futures-task v0.3.5
  Downloaded futures-sink v0.3.5
  Downloaded futures-util v0.3.5
  Downloaded futures-core v0.3.5
  Downloaded futures-channel v0.3.5
  Downloaded deno_core v0.45.0
  Downloaded num_cpus v1.13.0
  Downloaded serde_derive v1.0.110
  Downloaded ryu v1.0.4
  Downloaded filetime v0.2.10
  Downloaded once_cell v1.4.0
  Downloaded pin-project v0.4.17
  Downloaded futures-macro v0.3.5
  Downloaded proc-macro2 v1.0.13
  Downloaded syn v1.0.22
  Downloaded failure v0.1.8
  Downloaded quote v1.0.6
  Downloaded smallvec v1.4.0
  Downloaded pin-utils v0.1.0
  Downloaded xattr v0.2.2
  Downloaded pin-project-internal v0.4.17
  Downloaded addr2line v0.12.0
   Compiling libc v0.2.70
   Compiling proc-macro2 v1.0.13
   Compiling unicode-xid v0.2.0
   Compiling syn v1.0.22
   Compiling cfg-if v0.1.10
   Compiling gimli v0.21.0
   Compiling rustc-demangle v0.1.16
   Compiling object v0.19.0
   Compiling memchr v2.3.3
   Compiling proc-macro-nested v0.1.4
   Compiling futures-sink v0.3.5
   Compiling proc-macro-hack v0.5.15
   Compiling futures-core v0.3.5
   Compiling once_cell v1.4.0
   Compiling serde v1.0.110
   Compiling bitflags v1.2.1
   Compiling slab v0.4.2
   Compiling futures-io v0.3.5
   Compiling pin-utils v0.1.0
   Compiling matches v0.1.8
   Compiling futures v0.1.29
   Compiling cargo_gn v0.0.15
   Compiling smallvec v1.4.0
   Compiling ryu v1.0.4
   Compiling log v0.4.8
   Compiling percent-encoding v2.1.0
   Compiling itoa v0.4.5
   Compiling lazy_static v1.4.0
   Compiling downcast-rs v1.1.1
   Compiling futures-channel v0.3.5
   Compiling futures-task v0.3.5
   Compiling unicode-bidi v0.3.4
   Compiling unicode-normalization v0.1.12
   Compiling addr2line v0.12.0
   Compiling idna v0.2.0
   Compiling num_cpus v1.13.0
   Compiling filetime v0.2.10
   Compiling xattr v0.2.2
   Compiling backtrace v0.3.48
   Compiling quote v1.0.6
   Compiling tar v0.4.28
   Compiling url v2.1.1
   Compiling failure v0.1.8
   Compiling which v3.1.1
   Compiling rusty_v8 v0.4.2
   Compiling pin-project-internal v0.4.17
   Compiling futures-macro v0.3.5
   Compiling serde_derive v1.0.110
   Compiling pin-project v0.4.17
   Compiling futures-util v0.3.5
   Compiling futures-executor v0.3.5
   Compiling futures v0.3.5
   Compiling serde_json v1.0.53
   Compiling deno_core v0.45.0
   Compiling deno-tar v0.0.1 (/Users/user1/OneDrive/coding/deno-tar)
warning: unused import: `futures::future::FutureExt`
 --> src/lib.rs:8:5
  |
8 | use futures::future::FutureExt;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

    Finished dev [unoptimized + debuginfo] target(s) in 1m 50s
IL1019:deno-tar user1$ deno run -A --unstable examples/archive.ts 
INFO load deno plugin "deno_tar" from local "/Users/user1/OneDrive/coding/deno-tar/.deno_plugins/deno_tar_d7e79555a7a99803be0f927465a8de5d.dylib"
Bus error: 10
IL1019:deno-tar user1$ deno run -A --unstable examples/read.ts 
INFO load deno plugin "deno_tar" from local "/Users/user1/OneDrive/coding/deno-tar/.deno_plugins/deno_tar_d7e79555a7a99803be0f927465a8de5d.dylib"
Bus error: 10

**Comment by littledivy** [comment]
@bvenkatr Sorry for being late. I'll take a look at the issue.
Bus error 10 is a weird problem though.
